from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('register/', views.register, name='register'),
    path('task_<int:pk>/view/', views.task_detail, name='task_detail'),
    path('task_<int:pk>/edit/', views.edit_task, name='edit_task'),
    path('task/create/', views.create_task, name='create_task'),
    path('tasks/<int:task_id>/log-time/', views.log_time_entry, name='log_time_entry'),
    path('task_<int:pk>/update-description/', views.update_task_description, name='update_task_description'),
    path('backlog/', views.product_backlog, name='product_backlog'),
    path('sprint_<int:sprint_pk>/board/', views.sprint_board, name='sprint_board'),
    path('sprint_backlog/', views.sprint_backlog, name='sprint_backlog'),
    path('task/<int:task_pk>/move-to-sprint/<int:sprint_pk>/', views.move_to_sprint, name='move_to_sprint'),
    path('task/<int:task_pk>/sprint-progress/<str:new_progress>/', views.update_sprint_progress, name='update_sprint_progress'),
    path('sprint/create/', views.create_sprint, name='create_sprint'),
    path('sprint_<int:sprint_pk>/edit/', views.edit_sprint, name='edit_sprint'),
    path('sprint_<int:sprint_pk>/complete/', views.complete_sprint, name='complete_sprint'),
    path('sprint_<int:sprint_pk>/reopen/', views.reopen_sprint, name='reopen_sprint'),
    path('sprint_<int:sprint_pk>/burndown/', views.sprint_burndown, name='sprint_burndown'),
    path('testing/', views.testing_queue, name='testing_queue'),
    path('task_<int:pk>/ready-for-test/', views.mark_ready_for_test, name='mark_ready_for_test'),
    path('task_<int:pk>/pass-testing/', views.pass_testing, name='pass_testing'),
    path('task_<int:pk>/fail-testing/', views.fail_testing, name='fail_testing'),
    path('tasks/completed/', views.completed_tasks, name='completed_tasks'),
    path('sprint_<int:sprint_pk>/report/', views.sprint_report, name='sprint_report'),
    path('sprint_<int:sprint_pk>/report/export-csv/', views.export_sprint_report_csv, name='export_sprint_report_csv'),
    path('sprint_<int:sprint_pk>/report/export-pdf/', views.export_sprint_report_pdf, name='export_sprint_report_pdf'),
    path('sprint_<int:sprint_pk>/report/email/', views.email_sprint_report, name='email_sprint_report'),
]
