# Generated by Django 5.2.10 on 2026-03-21 01:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="estimated_hours",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="story_points",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
