# Generated by Django 5.2.10 on 2026-04-04 23:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_sprint_task_sprint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sprint",
            name="status",
            field=models.CharField(
                choices=[
                    ("NOT_STARTED", "Not Started"),
                    ("PLANNING", "Planning"),
                    ("ACTIVE", "Active"),
                    ("COMPLETED", "Completed"),
                ],
                default="NOT_STARTED",
                max_length=20,
            ),
        ),
    ]
