# Generated by Django 5.2.10 on 2026-04-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_alter_sprint_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="SPRINT_PROGRESS",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NOT_STARTED", "Not Started"),
                    ("IN_PROGRESS", "In Progress"),
                    ("IN_REVIEW", "In Review"),
                    ("DONE", "Done"),
                ],
                help_text="Progress of the task in the sprint",
                max_length=20,
                null=True,
            ),
        ),
    ]
