# Generated by Django 5.2.10 on 2026-04-05 21:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_task_sprint_progress"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="SPRINT_PROGRESS",
            new_name="sprint_progress",
        ),
    ]
