# Generated by Django 5.2.10 on 2026-04-17 00:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_rename_sprint_progress_task_sprint_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
