# Generated by Django 5.2.10 on 2026-04-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_task_completed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="failed_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="task",
            name="moved_to_testing_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="testing_notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
