# Generated by Django 5.2.10 on 2026-04-19 19:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_task_failed_count_task_moved_to_testing_at_and_more"),
        ("main", "0009_taskhistory"),
    ]

    operations = []
