# Generated by Django 5.2.10 on 2026-04-27 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_merge_20260419_1409"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="planned_sprint",
            field=models.ForeignKey(
                blank=True,
                help_text="Sprint this task was originally planned for (for metrics)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="planned_tasks",
                to="main.sprint",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="sprint",
            field=models.ForeignKey(
                blank=True,
                help_text="Current sprint this task is assigned to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_tasks",
                to="main.sprint",
            ),
        ),
    ]
