# Generated by Django 5.2.10 on 2026-04-27 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_task_planned_sprint_alter_task_sprint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="sprint",
            field=models.ForeignKey(
                blank=True,
                help_text="Current sprint this task is assigned to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="main.sprint",
            ),
        ),
    ]
