# Generated by Django 5.2.12 on 2026-04-30 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_timeentry'),
        ('main', '0012_alter_task_sprint'),
    ]

    operations = [
    ]
