# Generated by Django 5.2.12 on 2026-04-30 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_merge_0011_timeentry_0012_alter_task_sprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='story_points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
